name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  create-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag helloe_world:latest

    - name: Build and Push to DockerHub
    - uses: MaximilianoBz/dockerhub-buildpush@v1.1
    # You may pin to the exact commit or the version.
    # uses: MaximilianoBz/dockerhub-buildpush@372110d600041736063b948d05005b6039d8fb0c
      with:
      # Docker Registry Url, eg: docker.io
        registry_url: docker.io
        # Docker Image Repository Name, eg: username/demo-app
        repository_name: johntestactiondocker
        # Docker Login UserName, from: https://hub.docker.com/
        user_name: ${{ DOCKER_USERNAME}}
        # Docker Login Access Token, from: https://hub.docker.com/
        password: ${{ DOCKER_PASSWORD }}
        # Image Build Version
        image_version: latest
        # Docker File Directory, Default Current Directory (.)
        docker_file: .
          
