name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  create-image:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
    - uses: actions/checkout@v4
    - uses: MaximilianoBz/dockerhub-buildpush@v1.1
      with:
      # Docker Registry Url, eg: docker.io
        registry_url: docker.io
        # Docker Image Repository Name, eg: username/demo-app
        repository_name: johntestactiondocker
        # Docker Login UserName, from: https://hub.docker.com/
        user_name: ${{ DOCKER_USERNAME}}
        # Docker Login Access Token, from: https://hub.docker.com/
        password: ${{ DOCKER_PASSWORD }}
        # Image Build Version
        image_version: latest
        # Docker File Directory, Default Current Directory (.)
        docker_file: .
          
