#Instruktioner
#1. Lägg till en workflow_dispatch-trigger som tar in minst en input (till exempel sträng).
#2. Lägg till ett jobb som kör ett skript som visar upp värdet från inputen.
name: Uppgift 1 – Workflow Dispatch Input

on:
  workflow_dispatch:
    inputs:
      task_one_input_1:
        description: 'Add an input'
        required: true
      task_one_input_2:
        description: 'Add another input'
        type: boolean
        required: false
        default: false

jobs:
  printer:
    runs-on: ubuntu-latest
    steps:
    - name: print
      run: echo ${{ github.event.inputs.task_one }}
      #run: echo ${{ github.event.inputs.task_one == 'true' }}

#Vad händer om du inte anger något värde?
#Hur kan du lägga till fler inputs av olika typer (till exempel choice, boolean)?
